# Generated by Django 5.0.1 on 2024-02-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(max_length=200, null=True)),
                ('aadhaar', models.IntegerField()),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('aadhaar', models.IntegerField()),
                ('loginapproval', models.BooleanField(default=False)),
            ],
        ),
    ]
