# Generated by Django 5.0.1 on 2024-02-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_remove_booking_customer_booking_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='room_number',
        ),
    ]
