# Generated by Django 5.0.1 on 2024-02-08 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_rename_customer_name_booking_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='room_number',
            new_name='room',
        ),
    ]
