# Generated by Django 5.0.1 on 2024-02-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_rename_name_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
